/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as LaMarcaRouteImport } from './routes/la-marca'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as VisitanosRouteImport } from './routes/visitanos'
import { Route as CreacionesIndexRouteImport } from './routes/creaciones.index'
import { Route as CreacionesSlugRouteImport } from './routes/creaciones.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LaMarcaRoute = LaMarcaRouteImport.update({
  id: '/la-marca',
  path: '/la-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitanosRoute = VisitanosRouteImport.update({
  id: '/visitanos',
  path: '/visitanos',
  getParentRoute: () => rootRouteImport,
} as any)
const CreacionesIndexRoute = CreacionesIndexRouteImport.update({
  id: '/creaciones/',
  path: '/creaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreacionesSlugRoute = CreacionesSlugRouteImport.update({
  id: '/creaciones/$slug',
  path: '/creaciones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiencia': typeof ExperienciaRoute
  '/la-marca': typeof LaMarcaRoute
  '/menu': typeof MenuRoute
  '/reservas': typeof ReservasRoute
  '/visitanos': typeof VisitanosRoute
  '/creaciones/$slug': typeof CreacionesSlugRoute
  '/creaciones/': typeof CreacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiencia': typeof ExperienciaRoute
  '/la-marca': typeof LaMarcaRoute
  '/menu': typeof MenuRoute
  '/reservas': typeof ReservasRoute
  '/visitanos': typeof VisitanosRoute
  '/creaciones/$slug': typeof CreacionesSlugRoute
  '/creaciones': typeof CreacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiencia': typeof ExperienciaRoute
  '/la-marca': typeof LaMarcaRoute
  '/menu': typeof MenuRoute
  '/reservas': typeof ReservasRoute
  '/visitanos': typeof VisitanosRoute
  '/creaciones/$slug': typeof CreacionesSlugRoute
  '/creaciones/': typeof CreacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiencia'
    | '/la-marca'
    | '/menu'
    | '/reservas'
    | '/visitanos'
    | '/creaciones/$slug'
    | '/creaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiencia'
    | '/la-marca'
    | '/menu'
    | '/reservas'
    | '/visitanos'
    | '/creaciones/$slug'
    | '/creaciones'
  id:
    | '__root__'
    | '/'
    | '/experiencia'
    | '/la-marca'
    | '/menu'
    | '/reservas'
    | '/visitanos'
    | '/creaciones/$slug'
    | '/creaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienciaRoute: typeof ExperienciaRoute
  LaMarcaRoute: typeof LaMarcaRoute
  MenuRoute: typeof MenuRoute
  ReservasRoute: typeof ReservasRoute
  VisitanosRoute: typeof VisitanosRoute
  CreacionesSlugRoute: typeof CreacionesSlugRoute
  CreacionesIndexRoute: typeof CreacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-marca': {
      id: '/la-marca'
      path: '/la-marca'
      fullPath: '/la-marca'
      preLoaderRoute: typeof LaMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitanos': {
      id: '/visitanos'
      path: '/visitanos'
      fullPath: '/visitanos'
      preLoaderRoute: typeof VisitanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creaciones/': {
      id: '/creaciones/'
      path: '/creaciones'
      fullPath: '/creaciones/'
      preLoaderRoute: typeof CreacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creaciones/$slug': {
      id: '/creaciones/$slug'
      path: '/creaciones/$slug'
      fullPath: '/creaciones/$slug'
      preLoaderRoute: typeof CreacionesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienciaRoute: ExperienciaRoute,
  LaMarcaRoute: LaMarcaRoute,
  MenuRoute: MenuRoute,
  ReservasRoute: ReservasRoute,
  VisitanosRoute: VisitanosRoute,
  CreacionesSlugRoute: CreacionesSlugRoute,
  CreacionesIndexRoute: CreacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
